# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf-8
  database: style_guide_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf-8
  database: style_guide_test
  pool: 5
  username: postgres
  password:

